name: virgil_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  google_generative_ai: any
  flutter_markdown: ^0.7.4+2
  logger: ^1.0.0
  # google_maps_flutter: ^2.0.6
  # location: ^4.4.0
  provider: ^6.0.0 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
